/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.claudiodornelles.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Avro Schema for our customer */
@org.apache.avro.specific.AvroGenerated
public class Customer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1224316496843387853L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Customer\",\"namespace\":\"com.github.claudiodornelles.avro\",\"doc\":\"Avro Schema for our customer\",\"fields\":[{\"name\":\"firstName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Customer's first name\"},{\"name\":\"middleName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Customer's middle name\",\"default\":null},{\"name\":\"lastName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Customer's last name\"},{\"name\":\"age\",\"type\":\"int\",\"doc\":\"Customer's age\"},{\"name\":\"height\",\"type\":\"float\",\"doc\":\"Customer's height in centimeters\"},{\"name\":\"weight\",\"type\":\"float\",\"doc\":\"Customer's weight in Kilograms\"},{\"name\":\"automatedEmail\",\"type\":\"boolean\",\"doc\":\"true if the customer wants marketing emails\",\"default\":true}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Customer> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Customer> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Customer> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Customer> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Customer> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Customer to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Customer from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Customer instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Customer fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Customer's first name */
  private java.lang.String firstName;
  /** Customer's middle name */
  private java.lang.String middleName;
  /** Customer's last name */
  private java.lang.String lastName;
  /** Customer's age */
  private int age;
  /** Customer's height in centimeters */
  private float height;
  /** Customer's weight in Kilograms */
  private float weight;
  /** true if the customer wants marketing emails */
  private boolean automatedEmail;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Customer() {}

  /**
   * All-args constructor.
   * @param firstName Customer's first name
   * @param middleName Customer's middle name
   * @param lastName Customer's last name
   * @param age Customer's age
   * @param height Customer's height in centimeters
   * @param weight Customer's weight in Kilograms
   * @param automatedEmail true if the customer wants marketing emails
   */
  public Customer(java.lang.String firstName, java.lang.String middleName, java.lang.String lastName, java.lang.Integer age, java.lang.Float height, java.lang.Float weight, java.lang.Boolean automatedEmail) {
    this.firstName = firstName;
    this.middleName = middleName;
    this.lastName = lastName;
    this.age = age;
    this.height = height;
    this.weight = weight;
    this.automatedEmail = automatedEmail;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return firstName;
    case 1: return middleName;
    case 2: return lastName;
    case 3: return age;
    case 4: return height;
    case 5: return weight;
    case 6: return automatedEmail;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: firstName = value$ != null ? value$.toString() : null; break;
    case 1: middleName = value$ != null ? value$.toString() : null; break;
    case 2: lastName = value$ != null ? value$.toString() : null; break;
    case 3: age = (java.lang.Integer)value$; break;
    case 4: height = (java.lang.Float)value$; break;
    case 5: weight = (java.lang.Float)value$; break;
    case 6: automatedEmail = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return Customer's first name
   */
  public java.lang.String getFirstName() {
    return firstName;
  }



  /**
   * Gets the value of the 'middleName' field.
   * @return Customer's middle name
   */
  public java.lang.String getMiddleName() {
    return middleName;
  }



  /**
   * Gets the value of the 'lastName' field.
   * @return Customer's last name
   */
  public java.lang.String getLastName() {
    return lastName;
  }



  /**
   * Gets the value of the 'age' field.
   * @return Customer's age
   */
  public int getAge() {
    return age;
  }



  /**
   * Gets the value of the 'height' field.
   * @return Customer's height in centimeters
   */
  public float getHeight() {
    return height;
  }



  /**
   * Gets the value of the 'weight' field.
   * @return Customer's weight in Kilograms
   */
  public float getWeight() {
    return weight;
  }



  /**
   * Gets the value of the 'automatedEmail' field.
   * @return true if the customer wants marketing emails
   */
  public boolean getAutomatedEmail() {
    return automatedEmail;
  }



  /**
   * Creates a new Customer RecordBuilder.
   * @return A new Customer RecordBuilder
   */
  public static com.github.claudiodornelles.avro.Customer.Builder newBuilder() {
    return new com.github.claudiodornelles.avro.Customer.Builder();
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Customer RecordBuilder
   */
  public static com.github.claudiodornelles.avro.Customer.Builder newBuilder(com.github.claudiodornelles.avro.Customer.Builder other) {
    if (other == null) {
      return new com.github.claudiodornelles.avro.Customer.Builder();
    } else {
      return new com.github.claudiodornelles.avro.Customer.Builder(other);
    }
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Customer instance.
   * @param other The existing instance to copy.
   * @return A new Customer RecordBuilder
   */
  public static com.github.claudiodornelles.avro.Customer.Builder newBuilder(com.github.claudiodornelles.avro.Customer other) {
    if (other == null) {
      return new com.github.claudiodornelles.avro.Customer.Builder();
    } else {
      return new com.github.claudiodornelles.avro.Customer.Builder(other);
    }
  }

  /**
   * RecordBuilder for Customer instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Customer>
    implements org.apache.avro.data.RecordBuilder<Customer> {

    /** Customer's first name */
    private java.lang.String firstName;
    /** Customer's middle name */
    private java.lang.String middleName;
    /** Customer's last name */
    private java.lang.String lastName;
    /** Customer's age */
    private int age;
    /** Customer's height in centimeters */
    private float height;
    /** Customer's weight in Kilograms */
    private float weight;
    /** true if the customer wants marketing emails */
    private boolean automatedEmail;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.claudiodornelles.avro.Customer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.middleName)) {
        this.middleName = data().deepCopy(fields()[1].schema(), other.middleName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.age)) {
        this.age = data().deepCopy(fields()[3].schema(), other.age);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.height)) {
        this.height = data().deepCopy(fields()[4].schema(), other.height);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.weight)) {
        this.weight = data().deepCopy(fields()[5].schema(), other.weight);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.automatedEmail)) {
        this.automatedEmail = data().deepCopy(fields()[6].schema(), other.automatedEmail);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing Customer instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.claudiodornelles.avro.Customer other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.middleName)) {
        this.middleName = data().deepCopy(fields()[1].schema(), other.middleName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.age)) {
        this.age = data().deepCopy(fields()[3].schema(), other.age);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.height)) {
        this.height = data().deepCopy(fields()[4].schema(), other.height);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.weight)) {
        this.weight = data().deepCopy(fields()[5].schema(), other.weight);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.automatedEmail)) {
        this.automatedEmail = data().deepCopy(fields()[6].schema(), other.automatedEmail);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'firstName' field.
      * Customer's first name
      * @return The value.
      */
    public java.lang.String getFirstName() {
      return firstName;
    }


    /**
      * Sets the value of the 'firstName' field.
      * Customer's first name
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder setFirstName(java.lang.String value) {
      validate(fields()[0], value);
      this.firstName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * Customer's first name
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'firstName' field.
      * Customer's first name
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'middleName' field.
      * Customer's middle name
      * @return The value.
      */
    public java.lang.String getMiddleName() {
      return middleName;
    }


    /**
      * Sets the value of the 'middleName' field.
      * Customer's middle name
      * @param value The value of 'middleName'.
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder setMiddleName(java.lang.String value) {
      validate(fields()[1], value);
      this.middleName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'middleName' field has been set.
      * Customer's middle name
      * @return True if the 'middleName' field has been set, false otherwise.
      */
    public boolean hasMiddleName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'middleName' field.
      * Customer's middle name
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder clearMiddleName() {
      middleName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * Customer's last name
      * @return The value.
      */
    public java.lang.String getLastName() {
      return lastName;
    }


    /**
      * Sets the value of the 'lastName' field.
      * Customer's last name
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder setLastName(java.lang.String value) {
      validate(fields()[2], value);
      this.lastName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * Customer's last name
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastName' field.
      * Customer's last name
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * Customer's age
      * @return The value.
      */
    public int getAge() {
      return age;
    }


    /**
      * Sets the value of the 'age' field.
      * Customer's age
      * @param value The value of 'age'.
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder setAge(int value) {
      validate(fields()[3], value);
      this.age = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * Customer's age
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'age' field.
      * Customer's age
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder clearAge() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'height' field.
      * Customer's height in centimeters
      * @return The value.
      */
    public float getHeight() {
      return height;
    }


    /**
      * Sets the value of the 'height' field.
      * Customer's height in centimeters
      * @param value The value of 'height'.
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder setHeight(float value) {
      validate(fields()[4], value);
      this.height = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'height' field has been set.
      * Customer's height in centimeters
      * @return True if the 'height' field has been set, false otherwise.
      */
    public boolean hasHeight() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'height' field.
      * Customer's height in centimeters
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder clearHeight() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'weight' field.
      * Customer's weight in Kilograms
      * @return The value.
      */
    public float getWeight() {
      return weight;
    }


    /**
      * Sets the value of the 'weight' field.
      * Customer's weight in Kilograms
      * @param value The value of 'weight'.
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder setWeight(float value) {
      validate(fields()[5], value);
      this.weight = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'weight' field has been set.
      * Customer's weight in Kilograms
      * @return True if the 'weight' field has been set, false otherwise.
      */
    public boolean hasWeight() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'weight' field.
      * Customer's weight in Kilograms
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder clearWeight() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'automatedEmail' field.
      * true if the customer wants marketing emails
      * @return The value.
      */
    public boolean getAutomatedEmail() {
      return automatedEmail;
    }


    /**
      * Sets the value of the 'automatedEmail' field.
      * true if the customer wants marketing emails
      * @param value The value of 'automatedEmail'.
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder setAutomatedEmail(boolean value) {
      validate(fields()[6], value);
      this.automatedEmail = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'automatedEmail' field has been set.
      * true if the customer wants marketing emails
      * @return True if the 'automatedEmail' field has been set, false otherwise.
      */
    public boolean hasAutomatedEmail() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'automatedEmail' field.
      * true if the customer wants marketing emails
      * @return This builder.
      */
    public com.github.claudiodornelles.avro.Customer.Builder clearAutomatedEmail() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Customer build() {
      try {
        Customer record = new Customer();
        record.firstName = fieldSetFlags()[0] ? this.firstName : (java.lang.String) defaultValue(fields()[0]);
        record.middleName = fieldSetFlags()[1] ? this.middleName : (java.lang.String) defaultValue(fields()[1]);
        record.lastName = fieldSetFlags()[2] ? this.lastName : (java.lang.String) defaultValue(fields()[2]);
        record.age = fieldSetFlags()[3] ? this.age : (java.lang.Integer) defaultValue(fields()[3]);
        record.height = fieldSetFlags()[4] ? this.height : (java.lang.Float) defaultValue(fields()[4]);
        record.weight = fieldSetFlags()[5] ? this.weight : (java.lang.Float) defaultValue(fields()[5]);
        record.automatedEmail = fieldSetFlags()[6] ? this.automatedEmail : (java.lang.Boolean) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Customer>
    WRITER$ = (org.apache.avro.io.DatumWriter<Customer>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Customer>
    READER$ = (org.apache.avro.io.DatumReader<Customer>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.firstName);

    if (this.middleName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.middleName);
    }

    out.writeString(this.lastName);

    out.writeInt(this.age);

    out.writeFloat(this.height);

    out.writeFloat(this.weight);

    out.writeBoolean(this.automatedEmail);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.firstName = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.middleName = null;
      } else {
        this.middleName = in.readString();
      }

      this.lastName = in.readString();

      this.age = in.readInt();

      this.height = in.readFloat();

      this.weight = in.readFloat();

      this.automatedEmail = in.readBoolean();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.firstName = in.readString();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.middleName = null;
          } else {
            this.middleName = in.readString();
          }
          break;

        case 2:
          this.lastName = in.readString();
          break;

        case 3:
          this.age = in.readInt();
          break;

        case 4:
          this.height = in.readFloat();
          break;

        case 5:
          this.weight = in.readFloat();
          break;

        case 6:
          this.automatedEmail = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










